gcp:
  project: jason-hsbc
  region: europe-west2



modeling:
  model1:
    table1: DS1.tb_model1_house_price

gemini:
  api-key: "GEMINI-API-KEY"
  max-tokens: 8192
  
deepseek:
  api-key: "DEEPSEEK_API_KEY"
  base-url: "https://api.deepseek.com"
